inkbusters/models.py
from flask import current_app
from inkbusters import db


class Questions(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120), nullable=False)
    content = db.Column(db.Text, nullable=False)
    priority = db.Column(db.Integer, nullable=True)

    def __repr__(self):
        return f"{id}-{title}"

inkbusters/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Email


class ContactForm(FlaskForm):
    email = EmailField(
        "Email",
        validators=[DataRequired(), Email()],
        render_kw={"placeholder": "Adres e-mail"},
    )

    title = StringField(
        "Title",
        validators=[DataRequired()],
        render_kw={"placeholder": "Tytuł wiadomości"},
    )

    content = TextAreaField(
        "Content",
        validators=[DataRequired()],
        render_kw={"placeholder": "Treść wiadomości"},
    )
    submit = SubmitField("Wyślij")

inkbusters/__init__.py
import os

import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_assets import Bundle, Environment
from flask_admin.contrib.sqla import ModelView
from flask_admin import Admin
from flask_mail import Mail

from inkbusters.config import Config

db = SQLAlchemy()
migrate = Migrate()
mail = Mail()


css = Bundle(
    "css/base.css",
    "css/navbar.css",
    "css/footer.css",
    "css/index.css",
    "css/about.css",
    "css/contact.css",
    "css/gallery.css",
    "css/pricing.css",
    output="css/min/main.min.css",
    filters="cssmin",
)


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    sentry_sdk.init(
        dsn="https://808f85a0d46c4a9bae40fdb1e5f1d8f9@sentry.io/2006805",
        integrations=[FlaskIntegration()]
    )

    # init features
    db.init_app(app)
    migrate.init_app(app, db)
    app.debug = 0
    mail.init_app(app)
    admin = Admin(app)

    # assets
    assets = Environment(app)
    assets.register("main_css", css)

    # blueprints
    from inkbusters.main.routes import main

    app.register_blueprint(main)

    # # flask admin
    # from inkbusters.models import Questions

    # admin.add_view(ModelView(Questions, db.session))

    return app

inkbusters/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for

from inkbusters.main.forms import ContactForm
from inkbusters.main.faq import FAQ
from inkbusters.email import email_page
import smtplib


main = Blueprint("main", __name__)

CSS_TAG = "main-header-resize"


@main.route("/")
def index():
    return render_template("index.html", questions=FAQ)


@main.route("/about/")
def about():
    return render_template("about.html", css_tag=CSS_TAG)


@main.route("/pricing/")
def pricing():
    return render_template("pricing.html", css_tag=CSS_TAG)


@main.route("/gallery/")
def gallery():
    return render_template("gallery.html", css_tag=CSS_TAG)


@main.route("/contact/", methods=["GET", "POST"])
def contact():
    form = ContactForm()

    if request.method == "POST":
        if form.validate() == False:
            flash("Wszytskie pola są wymagane")

            return render_template("contact.html", css_tag=CSS_TAG, form=form)
        else:
            flash("Dziękujemy za wiadomość !")
            data = {
                'title': form.title.data,
                'email': form.email.data,
                'content': form.content.data
            }
            try:
                email_page(data)
            except smtplib.SMTPAuthenticationError as e:
                print(e)
                
            return redirect(url_for("main.index"))

    elif request.method == "GET":

        return render_template("contact.html", css_tag=CSS_TAG, form=form)


@main.route("/policy/")
def policy():
    return render_template("policy.html", css_tag=CSS_TAG)

inkbusters/templates/about.html
{% extends 'base.html' %}

{% block title %}O nas{% endblock %}

{% block header_title %} O nas {% endblock %}

{% block main %}
<div class="container">
    <section class="row first-box">
        <article class="col-12">
            <h2 class="col-12">Poznaj nasz team</h2>
            <span></span>
            <p class="col-12"> 
                <strong> Inkbusters </strong> to skład profesjonalistów, którzy 
                znając od podszewki cały proces wykonywania tatuażu potrafi doradzić najlepszy sposób zakrycia niechcianych prac.
                W salonie mają Państwo możliwość wybrania odpowiedniego tatuatora, który po procesie rozjaśniania wzoru przystąpi 
                do wykonywania covera. Na bierząco zatem  możemy kontrolować przebieg procesu usuwania i 
                przystąpić do coverowania gdy tylko będzie to możliwe.
            </p>
            <p class="col-12">
                Posiadamy laser o najmniejszym możliwie czasie impulsu wśród laserów Q-switch, a także od bardzo dużej moce. 
                Wskutek połaczenia tych cech naszego urządzenia, usuwanie tatuażu przebiega wydajniej bez nadmiernego uszkodzenia skóry.
            </p>
            <a href="{{ url_for('main.about') }}"> Dowiedz się więcej </a>
        </article>
    </section>
</div>

<section class="row team rotate">
    <div class="container"> 
        <div class="row team_main">
            <header class="col-12 anty-rotate">
                <h3> Nasz zespół </h3>
            </header>

            <div class="col-12 anty-rotate">
                <div class="row">
                    <article class="col-lg-6 col-xl-4">
                        <img src="{{ url_for('static', filename='images/profile/martyna.jpg')}}" alt="">
                        <h3>Martyna Gromadowska</h3>
                        <p>Właścicielka studia tatuażu "Pewnie Że Boli Tattoo". 
                            Od lat związana z tatuatorami i całym światem tatuaż.
                            Od roku także zajmuje się usuwaniem i z łatwością 
                            odpowiedniego tatuatora do zakrycia niechcianych prac.

                        </p>
                    </article>
                    <article class="col-lg-6 col-xl-4">
                        <img src="{{ url_for('static', filename='images/profile/adrian.jpg')}}" alt="">
                        <h3>Adrian Borowski</h3>
                        <p>Tatuator z wieloletnim doświadczeniem, od 4 lat pracuje w studiu "Pewnie Że Boli Tattoo".
                            Od roku także zajmuje się usuwaniem tatuaży oraz makijażu pernamentnego.
                            Prócz samego zabiegu usuwania z chęcia przedstawi pomysły jak zakryć niechciany tatuaż.


                        </p>
                    </article>
                    <article class="col-lg-6 col-xl-4">
                        <img src="{{ url_for('static', filename='images/profile/klaudia.jpg')}}" alt="">
                        <h3>Klaudia Tonak</h3>
                        <p>Managerka studia tatuażu "Pewnie ze Boli Tattoo". 
                            Na codzień zajmuje się kontaktem z klientemi oraz jest w trakcie
                            przyuczania się do zawodu tatuatora. Ma już na swoim koncie kilka tatuaży 
                            oraz posiada roczne doświadczenie w usuwaniu tatuaży.

                        </p>
                    </article>

                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %} 

inkbusters/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap-grid.min.css')}}">
    {% assets "main_css" %}
    <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
    {% endassets %}

    
    

    <title>Inkbusters - {% block title %}{% endblock %}</title>

    {% block meta %}{% endblock %}
</head>

<body>
    <!-- NAVBAR -->
    <nav class="navbar">

        <a class="navbar-logo" href="{{ url_for('main.index')}}">
            <img src="{{ url_for('static', filename='images/logo/logo_font_white.png')}}" alt="">
        </a>

        <ul class="navbar-links" id="js-menu">
            <li><a class="nav-links" href="{{ url_for('main.about') }}"> 
                O nas  </a></li>
            <li><a class="nav-links" href="{{ url_for('main.pricing') }}"> 
                Cennik  </a></li>
            <li><a class="nav-links" href="{{ url_for('main.gallery') }}"> 
                Galeria  </a></li>
            <li><a class="nav-links" href="{{ url_for('main.contact') }}"> 
                Kontakt  </a></li>
        </ul>

        <span class="navbar-toggle" id="js-navbar-toggle">
            <i class="menu-mobile"></i>
        </span>
    </nav>

    <!-- HEADER WITH PHOTO -->
    <header class="container-fluid main-header
    {% if css_tag %} {{ css_tag }} {% endif %}
    ">
        <img 
        src="{{ url_for('static', filename='images/other/header.jpg')}}" 
        alt="">
        
        <h2>{% block header_title %}{% endblock %}</h2>

    </header>

    <!-- MAIN BLOCK -->
    <main class="container-fluid" style="padding-top: 100px;">
        {% block main %}
        {% endblock %}  
    </main>
    
    <!-- FOOTER -->
    <footer class="container-fluid footer">
        <div class="container">
            <div class="row footer-main footer-margin">
                <a href="{{ url_for('main.index') }}" class="col-xl-3 footer-photo">
                    <img src="{{ url_for('static', filename='images/logo/logo_white.svg')}}">
                </a>
                <div class="col-12 col-lg-4 col-xl-3">
                    <ul class="footer-section">
                        <li class="footer-header">Rejestracja</li>
                        <li>+48 530 072 575</li>
                        <li>+48 530 072 575</li>
                        <li>contact@inkbusters.pl</li>
                    </ul>
                </div>
                <div class="col-12 col-lg-4 col-xl-3">
                    <ul class="footer-section">
                        <li class="footer-header">Godziny otwarcia</li>
                        <li>Pon-Pt 11:00-18:00</li>
                        <li>Sob 11:00-15:00</li>
                        <li>Nd nieczynne</li>
                    </ul>
                </div>
                <div class="col-12 col-lg-4 col-xl-3">
                    <ul class="footer-section">
                        <li class="footer-header">Odwiedź nas osobiście</li>
                        <li>Pewnie Że Boli Tattoo</li>
                        <li>ul.Wszystkich Świętych 5</li>
                        <li>60-123 Poznań</li>
                    </ul>
                </div>
            </div>
        </div>
        
            <div class="footer-bottom">
                <div class="container">
                    <div class="row footer-margin">
                        <div class="col-12 col-sm-6 footer-bottom_left">
                            Inkbusters Copyright &copy; 2020
                        </div>
                        <div class="col-12 col-sm-6 footer-bottom_right">
                            <ul>
                                <li><a href="">Inkbusters</a href="{{ url_for('main.index')}}"></li>
                                <li><a href="">
                                        <img src="{{ url_for('static', filename='images/icons/facebook.svg')}}" alt="">
                                    </a>
                                </li>
                                <li><a href="">
                                    <img src="{{ url_for('static', filename='images/icons/instagram.svg')}}" alt="">
                                </a>
                            </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
    </footer>

<!-- SCRIPTS -->
<script src="{{ url_for('static', filename='js/navbar.js')}}"></script>
</body>
</html>

inkbusters/templates/contact.html
{% extends 'base.html' %}

{% block title %}Kontakt{% endblock %}

{% block header_title %} Kontakt {% endblock %}

{% block main %}

<div class="container">
    <section class="row contact">
        <div class="col-lg-1"></div>

        <div class="col-lg-10">
            <div class="row">
                <article class="col-lg-6 contact-info">

                    <ul class="">
                        <li class="contact-info_header">Rejestracja</li>
                        <li>+48 530 072 575</li>
                        <li>+48 530 072 575</li>
                        <li>contact@inkbusters.pl</li>
                    </ul>

                    <ul class="">
                        <li class="contact-info_header">Godziny otwarcia</li>
                        <li>Pon-Pt 11:00-18:00</li>
                        <li>Sob 11:00-15:00</li>
                        <li>Nd nieczynne</li>
                    </ul>

                    <ul class="">
                        <li class="contact-info_header">Odwiedź nas osobiście</li>
                        <li>Pewnie Że Boli Tattoo</li>
                        <li>ul.Wszystkich Świętych 5</li>
                        <li>60-123 Poznań</li>
                    </ul>
                    <div class="navigate-button">
                        <a 
                            href="https://www.google.com/maps/dir//Pewnie+%C5%BBe+Boli+Tattoo,+Ulica+Wszystkich+%C5%9Awi%C4%99tych+5,+61-843+Pozna%C5%84/@52.4058268,16.9371027,19z/data=!4m8!4m7!1m0!1m5!1m1!1s0x47045b3f61f12b41:0x65cedb800e88889c!2m2!1d16.938035!2d52.405759"> 
                            Nawiguj 
                        </a>
                    </div> 

                </article>

                <!-- contact form -->
                <div class="col-lg-6 ">
                    <div class="contact-form"> 
                        <h3> Formularz kontaktowy</h3>
                        <form method="POST" action="{{ url_for('main.contact') }}">
                            {{ form.hidden_tag() }}
                            <div class="row">
                                <div class="col-12">
                                    {{form.email}}
                                </div>
                                <div class="col-12">
                                    {{form.title}}
                                </div>
                                <div class="col-12">
                                    {{form.content}}
                                </div>
                                <div class="col-10 contact-form_policy">
                                    Wysłanie wiadomości przy pomocy formularza oznacza akceptacje 
                                    <a >regulaminu</a> 
                                    dotyczącego zasad przetwarzania danych osobowych
                                </div>
                                <div class="col-12 contact-form_button">
                                    {{form.submit}}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-1"></div>
    </section>
</div>

{% endblock %} 

inkbusters/templates/gallery.html
{% extends 'base.html' %}

{% block title %}Galeria{% endblock %}

{% block header_title %} Galleria {% endblock %}

{% block main %}

<div class="container">
    <div class="row gallery">

    {% for section in range(1,5) %}
        <section class="col-12">
            <div class="row">

                {% for photo in ['before', 'first', 'second'] %}
                    <div class="col-12 col-md-4 gallery-box">
                        <div class="gallery-box_image">
                            <img 
                            src="{{ url_for('static', filename='images/gallery/' + section|string + '/' + photo + '.jpg' ) }}" 
                            alt="">
                        </div>
                        <span class="gallery-box_text">
                            {% if photo == 'before' %}
                                Przed pierwszym zabiegiem
                            {% elif photo == 'first' %}
                                Po pierwszym zabiegu
                            {% else %}
                                Po drugim zabiegu
                            {% endif %}
                        </span>
                    </div>
                {% endfor %}

            </div>
        </section>
    {% endfor %}

    </div>
</div>

{% endblock %} 

inkbusters/templates/index.html
{% extends 'base.html' %}

{% block title %}Strona główna{% endblock %}

{% block header_title %}Laserowe  usuwanie tatuaży<br>metodą Q-switch{% endblock %}

{% block main %}
<div class="container">
    <section class="row first-box">
        <article class="col-12">
            <h2 class="col-12">Profesjonaliści w jednym miejscu</h2>
            <span></span>
            <p class="col-12"> 
                <strong> Inkbusters </strong> to więcej niż usuwanie laserowe. To zespół ludzi, 
                którzy na codzień zajmują się wykonywaniem tatuażu, 
                lub mają bardzo bliski kontakt ze światem modyfikacji ciała. 
                Już podczas samego zabiegu usuwania metodą Q-switch mamy możliwość 
                lepszego dobrania parametrów zabiegu znając od podszewki cały proces 
                wykonywania tatuażu. 
            </p>
            <a href="{{ url_for('main.about') }}"> Dowiedz się więcej </a>
        </article>
    </section>
</div>


<section class="row why-us rotate">
    <div class="container"> 
        <div class="row why-us_main">
            <header class="col-12 anty-rotate">
                <h3> Dlaczego my</h3>
            </header>

            <div class="col-12 anty-rotate">
                <div class="row">
                    <article class="col-lg-6 col-xl-3">
                        <h3>Doświadczenie</h3>
                        <span class="why-us_line"></span>
                        <p>
                            Cały zespół jest złożony z osób posiadajaych od 
                            wielu lat bezpośredni kontakt ze światem tatuażu, 
                            piercingu i makijażu pernamentego.  
                            Wiemy jak usuwać, ponieważ znamy odposzewki proces wykonywania tatuażu.
                        </p>
                    </article>

                    <article class="col-lg-6 col-xl-3">
                        <h3>Fachowy sprzęt</h3>
                        <span class="why-us_line"></span >
                        <p>
                            Pracujemy na laserze Q-switch z najwyżej półki. 
                            Cechuje się najniższym czasem impulsu oraz bardzo dużej mocy, 
                            pozwalającej na efektywne usuwanie tatuażu bez najdmiernego uszkodzenia skóry.
                        </p>
                    </article>

                    <article class="col-lg-6 col-xl-3">
                        <h3>Atrakcyjna cena</h3>
                        <span class="why-us_line"></span>
                        <p>
                            Usuwanie nie jest naszym jedynym żródłem dochodu, 
                            ponieważ cały zaspół zajmuje sie na codzień wykonywaniem 
                            tatuaży/makijażu pernamentego lub obsługa studia, 
                            stąd mamy bardzo atrkaycjne ceny za zabiegi.
                        </p>
                    </article>

                    <article class="col-lg-6 col-xl-3">
                        <h3>Profesjonalna obsługa</h3>
                        <span class="why-us_line"></span>
                        <p>
                            Prócz samego zabiegu usuwania dajemy możliwosć porozmiawaina z 
                            tatuatorami by zaplanować już na samym początku zakrycie 
                            tatuażu inną pracą w stylistyce, która będzie Ci najbardziej odpowiadać.
                        </p>
                    </article>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- second box photo -->
<div class="row second-box">
    <section class="container">
        <div class="row">
            <h2 class="col-12">Nasza Oferta</h2>
            <div class="col-12">
                <div class="row">
                    <span class="col-12 col-md-4"> Usuwanie tatuażu</span>
                    <span class="col-12 col-md-4"> Usuwanie makijazu pernamentnego</span>
                    <span class="col-12 col-md-4"> Profesjonalna konsultacja</span>
                </div>
            </div>
            <a class="col-12" href="{{ url_for('main.pricing') }}"> Zobacz cennik</a>
        </div>
    </section>
</div>


<section class="row faq rotate">
    <div class="container"> 
        <div class="row faq_main anty-rotate">
            <header class="col-12 ">
                <h3> Najczęstsze pytania</h3>
            </header>

            <!-- article -->
            {% for question in questions %}
            <div class="col-12 ">
                <div class="row">
                    <div class="display-none display-md-fixed col-md-1 col-lg-2"> </div>
                    <article class="col-12 col-md-10 col-lg-8">
                        <h3>{{ question.title }}</h3>
                        <p>{{ question.content }}</p>
                        <span class="faq_line"></span>
                    </article>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>
{% endblock %} 

inkbusters/templates/policy.html
{% extends 'base.html' %}

{% block title %}Polityka prywatności{% endblock %}

{% block header_title %} Polityka prywatności {% endblock %}

{% block main %}
{% endblock %} 

inkbusters/templates/pricing.html
{% extends 'base.html' %}

{% block title %}Cennik{% endblock %}

{% block header_title %} Cennik {% endblock %}

{% block main %}

    <div class="container">
        <section class="row price">
            <div class="col-lg-1"></div>
            <div class="col-lg-8">
                <article class="price-main">
                    <h2>Laserowe usuwanie tatuażu</h2>
                    <p>Ceny dotyczą tatuaży czarnych i szarych, przy kolorowych
                        cena może nieznacznie wzrosnąć</p>
                        <ul>
                            <li>
                                <span class="price-main_price">100zł</span>
                                <span class="price-main_desc">Kreski/kropki</span>
                            </li>
                            <li>
                                <span class="price-main_price">100-150zł</span>
                                <span class="price-main_desc">Tatuaż konturowy do 20cm2</span>
                            </li>
                            <li>
                                <span class="price-main_price">150-250zł</span>
                                <span class="price-main_desc">Tatuaż konturowy, ok. 45cm2 (wizytówka 9/5cm)</span>
                            </li>
                            <li>
                                <span class="price-main_price">250-300zł</span>
                                <span class="price-main_desc">Większy tatuaż konturowy lub pełny do 60cm2</span>
                            </li>
                            <li>
                                <span class="price-main_price">350-600zł</span>
                                <span class="price-main_desc">Bardzo duży tatuaż konturowy lub duży pełny</span>
                            </li>
                        </ul>
                </article>

                <article class="price-main">
                    <h2>Laserowe usuwania makijażu permanentnego</h2>
                    <p>Ceny dotyczą makijaży o barwie czarnej, ciemnobrązowej i brązowej. W przypadku innych kolorów cena może się różnić.</p>
                    <ul>
                        <li>
                            <span class="price-main_price">150-200zł</span>
                            <span class="price-main_desc">Kreski wokół ust</span>
                        </li>
                        <li>
                            <span class="price-main_price">150-300zł</span>
                            <span class="price-main_desc">Brwi</span>
                        </li>
                    </ul>
                </article>

                
            </div>

            <p class=" col-12 price-discount">Przy zapisie na min. 5 sesji obowiązuje zniżka 15%</p>
        </section>
    </div>
{% endblock %} 